name: CI Workflow

# Trigger the workflow when pushing to the main branch or on pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs to run on specific environments
jobs:
  build:
    runs-on: ubuntu-latest  # Specify the environment (OS) to run the job

    steps:
    # Step 1: Checkout the latest code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python (you can change this to your required environment)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies (you can change this depending on your project)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run your tests
    - name: Run tests
      run: |
        pytest
